version: "2"

services:
    factomd_0:
        container_name: factomd_0
        image: factominc/factomd:v6.6.0
        #build: ../../
        #image: factomproject/factomd:dev
        #build: ../../
        depends_on:
            - logstash
            - nginx
        expose:
            - "8088"
            - "8110"
        ports:
            - "8090:8090"
        volumes:
            - ./factom/factomd_1.conf:/root/.factom/m2/factomd.conf:ro
        command: -sim_stdin=false -nodename=Fnode0 -customnet=net -network=CUSTOM -blktime=15 -logstash -logurl=logstash:8345
        networks:
            factomd:
                ipv4_address: 10.7.0.1

    factomd_1:
        container_name: factomd_1
        image: factominc/factomd:v6.6.0
        #build: ../../
        #image: factomproject/factomd:dev
        depends_on:
            - logstash
            - nginx
        expose:
            - "8088"
            - "8110"
        ports:
            - "8190:8090"
        volumes:
            - ./factom/factomd_2.conf:/root/.factom/m2/factomd.conf:ro
        command: -sim_stdin=false -nodename=Fnode1 -customnet=net -network=CUSTOM -blktime=15 -logstash -logurl=logstash:8345
        networks:
            factomd:
                ipv4_address: 10.7.0.2

    factomd_2:
        container_name: factomd_2
        image: factominc/factomd:v6.6.0
        #build: ../../
        #image: factomproject/factomd:dev
        depends_on:
            - logstash
            - nginx
        expose:
            - "8088"
            - "8110"
        ports:
            - "8290:8090"
        volumes:
            - ./factom/factomd_3.conf:/root/.factom/m2/factomd.conf:ro
        command: -sim_stdin=false -nodename=Fnode2 -customnet=net -network=CUSTOM -blktime=15 -logstash -logurl=logstash:8345
        networks:
            factomd:
                ipv4_address: 10.7.0.3

    elasticsearch:
        container_name: elasticsearch
        build:
            context: elasticsearch/
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        expose:
            - "9200"
            - "9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk

    logstash:
        container_name: logstash
        build:
            context: logstash/
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        expose:
            - "5000"
            - "9600"
            - "8345"
        ports:
            - "5000:5000"
            - "9600:9600"
            - "8345:8345"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk
            - factomd
        depends_on:
            - elasticsearch

    kibana:
        container_name: kibana
        build:
            context: kibana/
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        ports:
            - "5601:5601"
        networks:
            - elk
        depends_on:
            - elasticsearch

    prometheus:
        container_name: prometheus
        build:
            context: prometheus/
        volumes:
            - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - factomd
        depends_on:
            - factomd_0
            - factomd_1
            - factomd_2

    nginx:
        container_name: nginx
        build:
            context: nginx/
        volumes:
            - ./nginx/html/:/usr/share/nginx/html/:ro
        expose:
            - "80"
        networks:
            - factomd

networks:
    factomd:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.7.0.0/16
                  gateway: 10.7.1.1
                  ip_range: 10.7.1.0/24
    elk:
        driver: bridge
