global:
    scrape_interval:     60s # By default, scrape targets every 15 seconds.
    evaluation_interval: 60s # By default, scrape targets every 15 seconds.
    # scrape_timeout is set to the global default (10s).

    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: 'factomd'

scrape_configs:
    - job_name: factomd
      static_configs:
          - targets:
              - 'localhost:9876'
